//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Mews.Eet.EetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3", ConfigurationName="EetService.EET")]
    public interface EET {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fs.mfcr.cz/eet/OdeslaniTrzby", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mews.Eet.EetService.OdeslaniTrzbyResponse OdeslaniTrzby(Mews.Eet.EetService.OdeslaniTrzbyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://fs.mfcr.cz/eet/OdeslaniTrzby", ReplyAction="*")]
        System.Threading.Tasks.Task<Mews.Eet.EetService.OdeslaniTrzbyResponse> OdeslaniTrzbyAsync(Mews.Eet.EetService.OdeslaniTrzbyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class TrzbaHlavickaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uuid_zpravyField;
        
        private System.DateTime dat_odeslField;
        
        private bool prvni_zaslaniField;
        
        private bool overeniField;
        
        private bool overeniFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid_zpravy {
            get {
                return this.uuid_zpravyField;
            }
            set {
                this.uuid_zpravyField = value;
                this.RaisePropertyChanged("uuid_zpravy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_odesl {
            get {
                return this.dat_odeslField;
            }
            set {
                this.dat_odeslField = value;
                this.RaisePropertyChanged("dat_odesl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool prvni_zaslani {
            get {
                return this.prvni_zaslaniField;
            }
            set {
                this.prvni_zaslaniField = value;
                this.RaisePropertyChanged("prvni_zaslani");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool overeni {
            get {
                return this.overeniField;
            }
            set {
                this.overeniField = value;
                this.RaisePropertyChanged("overeni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overeniSpecified {
            get {
                return this.overeniFieldSpecified;
            }
            set {
                this.overeniFieldSpecified = value;
                this.RaisePropertyChanged("overeniSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedVarovaniType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kod_varovField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int kod_varov {
            get {
                return this.kod_varovField;
            }
            set {
                this.kod_varovField = value;
                this.RaisePropertyChanged("kod_varov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedChybaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kodField;
        
        private bool testField;
        
        private bool testFieldSpecified;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testSpecified {
            get {
                return this.testFieldSpecified;
            }
            set {
                this.testFieldSpecified = value;
                this.RaisePropertyChanged("testSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedPotvrzeniType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fikField;
        
        private bool testField;
        
        private bool testFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fik {
            get {
                return this.fikField;
            }
            set {
                this.fikField = value;
                this.RaisePropertyChanged("fik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testSpecified {
            get {
                return this.testFieldSpecified;
            }
            set {
                this.testFieldSpecified = value;
                this.RaisePropertyChanged("testSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class OdpovedHlavickaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uuid_zpravyField;
        
        private string bkpField;
        
        private System.DateTime dat_prijField;
        
        private bool dat_prijFieldSpecified;
        
        private System.DateTime dat_odmitField;
        
        private bool dat_odmitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid_zpravy {
            get {
                return this.uuid_zpravyField;
            }
            set {
                this.uuid_zpravyField = value;
                this.RaisePropertyChanged("uuid_zpravy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bkp {
            get {
                return this.bkpField;
            }
            set {
                this.bkpField = value;
                this.RaisePropertyChanged("bkp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_prij {
            get {
                return this.dat_prijField;
            }
            set {
                this.dat_prijField = value;
                this.RaisePropertyChanged("dat_prij");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dat_prijSpecified {
            get {
                return this.dat_prijFieldSpecified;
            }
            set {
                this.dat_prijFieldSpecified = value;
                this.RaisePropertyChanged("dat_prijSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_odmit {
            get {
                return this.dat_odmitField;
            }
            set {
                this.dat_odmitField = value;
                this.RaisePropertyChanged("dat_odmit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dat_odmitSpecified {
            get {
                return this.dat_odmitFieldSpecified;
            }
            set {
                this.dat_odmitFieldSpecified = value;
                this.RaisePropertyChanged("dat_odmitSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class BkpElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BkpDigestType digestField;
        
        private BkpEncodingType encodingField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BkpDigestType digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
                this.RaisePropertyChanged("digest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BkpEncodingType encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum BkpDigestType {
        
        /// <remarks/>
        SHA1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum BkpEncodingType {
        
        /// <remarks/>
        base16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class PkpElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PkpDigestType digestField;
        
        private PkpCipherType cipherField;
        
        private PkpEncodingType encodingField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PkpDigestType digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
                this.RaisePropertyChanged("digest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PkpCipherType cipher {
            get {
                return this.cipherField;
            }
            set {
                this.cipherField = value;
                this.RaisePropertyChanged("cipher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PkpEncodingType encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum PkpDigestType {
        
        /// <remarks/>
        SHA256,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum PkpCipherType {
        
        /// <remarks/>
        RSA2048,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public enum PkpEncodingType {
        
        /// <remarks/>
        base64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class TrzbaKontrolniKodyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PkpElementType pkpField;
        
        private BkpElementType bkpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PkpElementType pkp {
            get {
                return this.pkpField;
            }
            set {
                this.pkpField = value;
                this.RaisePropertyChanged("pkp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BkpElementType bkp {
            get {
                return this.bkpField;
            }
            set {
                this.bkpField = value;
                this.RaisePropertyChanged("bkp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3")]
    public partial class TrzbaDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dic_poplField;
        
        private string dic_poverujicihoField;
        
        private int id_provozField;
        
        private string id_poklField;
        
        private string porad_cisField;
        
        private System.DateTime dat_trzbyField;
        
        private decimal celk_trzbaField;
        
        private decimal zakl_nepodl_dphField;
        
        private bool zakl_nepodl_dphFieldSpecified;
        
        private decimal zakl_dan1Field;
        
        private bool zakl_dan1FieldSpecified;
        
        private decimal dan1Field;
        
        private bool dan1FieldSpecified;
        
        private decimal zakl_dan2Field;
        
        private bool zakl_dan2FieldSpecified;
        
        private decimal dan2Field;
        
        private bool dan2FieldSpecified;
        
        private decimal zakl_dan3Field;
        
        private bool zakl_dan3FieldSpecified;
        
        private decimal dan3Field;
        
        private bool dan3FieldSpecified;
        
        private decimal cest_sluzField;
        
        private bool cest_sluzFieldSpecified;
        
        private decimal pouzit_zboz1Field;
        
        private bool pouzit_zboz1FieldSpecified;
        
        private decimal pouzit_zboz2Field;
        
        private bool pouzit_zboz2FieldSpecified;
        
        private decimal pouzit_zboz3Field;
        
        private bool pouzit_zboz3FieldSpecified;
        
        private decimal urceno_cerp_zuctField;
        
        private bool urceno_cerp_zuctFieldSpecified;
        
        private decimal cerp_zuctField;
        
        private bool cerp_zuctFieldSpecified;
        
        private int rezimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_popl {
            get {
                return this.dic_poplField;
            }
            set {
                this.dic_poplField = value;
                this.RaisePropertyChanged("dic_popl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dic_poverujiciho {
            get {
                return this.dic_poverujicihoField;
            }
            set {
                this.dic_poverujicihoField = value;
                this.RaisePropertyChanged("dic_poverujiciho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id_provoz {
            get {
                return this.id_provozField;
            }
            set {
                this.id_provozField = value;
                this.RaisePropertyChanged("id_provoz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_pokl {
            get {
                return this.id_poklField;
            }
            set {
                this.id_poklField = value;
                this.RaisePropertyChanged("id_pokl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string porad_cis {
            get {
                return this.porad_cisField;
            }
            set {
                this.porad_cisField = value;
                this.RaisePropertyChanged("porad_cis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_trzby {
            get {
                return this.dat_trzbyField;
            }
            set {
                this.dat_trzbyField = value;
                this.RaisePropertyChanged("dat_trzby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal celk_trzba {
            get {
                return this.celk_trzbaField;
            }
            set {
                this.celk_trzbaField = value;
                this.RaisePropertyChanged("celk_trzba");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_nepodl_dph {
            get {
                return this.zakl_nepodl_dphField;
            }
            set {
                this.zakl_nepodl_dphField = value;
                this.RaisePropertyChanged("zakl_nepodl_dph");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_nepodl_dphSpecified {
            get {
                return this.zakl_nepodl_dphFieldSpecified;
            }
            set {
                this.zakl_nepodl_dphFieldSpecified = value;
                this.RaisePropertyChanged("zakl_nepodl_dphSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dan1 {
            get {
                return this.zakl_dan1Field;
            }
            set {
                this.zakl_dan1Field = value;
                this.RaisePropertyChanged("zakl_dan1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dan1Specified {
            get {
                return this.zakl_dan1FieldSpecified;
            }
            set {
                this.zakl_dan1FieldSpecified = value;
                this.RaisePropertyChanged("zakl_dan1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan1 {
            get {
                return this.dan1Field;
            }
            set {
                this.dan1Field = value;
                this.RaisePropertyChanged("dan1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan1Specified {
            get {
                return this.dan1FieldSpecified;
            }
            set {
                this.dan1FieldSpecified = value;
                this.RaisePropertyChanged("dan1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dan2 {
            get {
                return this.zakl_dan2Field;
            }
            set {
                this.zakl_dan2Field = value;
                this.RaisePropertyChanged("zakl_dan2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dan2Specified {
            get {
                return this.zakl_dan2FieldSpecified;
            }
            set {
                this.zakl_dan2FieldSpecified = value;
                this.RaisePropertyChanged("zakl_dan2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan2 {
            get {
                return this.dan2Field;
            }
            set {
                this.dan2Field = value;
                this.RaisePropertyChanged("dan2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan2Specified {
            get {
                return this.dan2FieldSpecified;
            }
            set {
                this.dan2FieldSpecified = value;
                this.RaisePropertyChanged("dan2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal zakl_dan3 {
            get {
                return this.zakl_dan3Field;
            }
            set {
                this.zakl_dan3Field = value;
                this.RaisePropertyChanged("zakl_dan3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakl_dan3Specified {
            get {
                return this.zakl_dan3FieldSpecified;
            }
            set {
                this.zakl_dan3FieldSpecified = value;
                this.RaisePropertyChanged("zakl_dan3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dan3 {
            get {
                return this.dan3Field;
            }
            set {
                this.dan3Field = value;
                this.RaisePropertyChanged("dan3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dan3Specified {
            get {
                return this.dan3FieldSpecified;
            }
            set {
                this.dan3FieldSpecified = value;
                this.RaisePropertyChanged("dan3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal cest_sluz {
            get {
                return this.cest_sluzField;
            }
            set {
                this.cest_sluzField = value;
                this.RaisePropertyChanged("cest_sluz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cest_sluzSpecified {
            get {
                return this.cest_sluzFieldSpecified;
            }
            set {
                this.cest_sluzFieldSpecified = value;
                this.RaisePropertyChanged("cest_sluzSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pouzit_zboz1 {
            get {
                return this.pouzit_zboz1Field;
            }
            set {
                this.pouzit_zboz1Field = value;
                this.RaisePropertyChanged("pouzit_zboz1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pouzit_zboz1Specified {
            get {
                return this.pouzit_zboz1FieldSpecified;
            }
            set {
                this.pouzit_zboz1FieldSpecified = value;
                this.RaisePropertyChanged("pouzit_zboz1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pouzit_zboz2 {
            get {
                return this.pouzit_zboz2Field;
            }
            set {
                this.pouzit_zboz2Field = value;
                this.RaisePropertyChanged("pouzit_zboz2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pouzit_zboz2Specified {
            get {
                return this.pouzit_zboz2FieldSpecified;
            }
            set {
                this.pouzit_zboz2FieldSpecified = value;
                this.RaisePropertyChanged("pouzit_zboz2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pouzit_zboz3 {
            get {
                return this.pouzit_zboz3Field;
            }
            set {
                this.pouzit_zboz3Field = value;
                this.RaisePropertyChanged("pouzit_zboz3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pouzit_zboz3Specified {
            get {
                return this.pouzit_zboz3FieldSpecified;
            }
            set {
                this.pouzit_zboz3FieldSpecified = value;
                this.RaisePropertyChanged("pouzit_zboz3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal urceno_cerp_zuct {
            get {
                return this.urceno_cerp_zuctField;
            }
            set {
                this.urceno_cerp_zuctField = value;
                this.RaisePropertyChanged("urceno_cerp_zuct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool urceno_cerp_zuctSpecified {
            get {
                return this.urceno_cerp_zuctFieldSpecified;
            }
            set {
                this.urceno_cerp_zuctFieldSpecified = value;
                this.RaisePropertyChanged("urceno_cerp_zuctSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal cerp_zuct {
            get {
                return this.cerp_zuctField;
            }
            set {
                this.cerp_zuctField = value;
                this.RaisePropertyChanged("cerp_zuct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cerp_zuctSpecified {
            get {
                return this.cerp_zuctFieldSpecified;
            }
            set {
                this.cerp_zuctFieldSpecified = value;
                this.RaisePropertyChanged("cerp_zuctSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rezim {
            get {
                return this.rezimField;
            }
            set {
                this.rezimField = value;
                this.RaisePropertyChanged("rezim");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Trzba", WrapperNamespace="http://fs.mfcr.cz/eet/schema/v3", IsWrapped=true)]
    public partial class OdeslaniTrzbyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3", Order=0)]
        public Mews.Eet.EetService.TrzbaHlavickaType Hlavicka;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3", Order=1)]
        public Mews.Eet.EetService.TrzbaDataType Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3", Order=2)]
        public Mews.Eet.EetService.TrzbaKontrolniKodyType KontrolniKody;
        
        public OdeslaniTrzbyRequest() {
        }
        
        public OdeslaniTrzbyRequest(Mews.Eet.EetService.TrzbaHlavickaType Hlavicka, Mews.Eet.EetService.TrzbaDataType Data, Mews.Eet.EetService.TrzbaKontrolniKodyType KontrolniKody) {
            this.Hlavicka = Hlavicka;
            this.Data = Data;
            this.KontrolniKody = KontrolniKody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Odpoved", WrapperNamespace="http://fs.mfcr.cz/eet/schema/v3", IsWrapped=true)]
    public partial class OdeslaniTrzbyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3", Order=0)]
        public Mews.Eet.EetService.OdpovedHlavickaType Hlavicka;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Chyba", typeof(OdpovedChybaType))]
        [System.Xml.Serialization.XmlElementAttribute("Potvrzeni", typeof(OdpovedPotvrzeniType))]
        public object Item;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fs.mfcr.cz/eet/schema/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("Varovani")]
        public Mews.Eet.EetService.OdpovedVarovaniType[] Varovani;
        
        public OdeslaniTrzbyResponse() {
        }
        
        public OdeslaniTrzbyResponse(Mews.Eet.EetService.OdpovedHlavickaType Hlavicka, object Item, Mews.Eet.EetService.OdpovedVarovaniType[] Varovani) {
            this.Hlavicka = Hlavicka;
            this.Item = Item;
            this.Varovani = Varovani;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EETChannel : Mews.Eet.EetService.EET, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EETClient : System.ServiceModel.ClientBase<Mews.Eet.EetService.EET>, Mews.Eet.EetService.EET {
        
        public EETClient() {
        }
        
        public EETClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EETClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EETClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EETClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mews.Eet.EetService.OdeslaniTrzbyResponse Mews.Eet.EetService.EET.OdeslaniTrzby(Mews.Eet.EetService.OdeslaniTrzbyRequest request) {
            return base.Channel.OdeslaniTrzby(request);
        }
        
        public Mews.Eet.EetService.OdpovedHlavickaType OdeslaniTrzby(Mews.Eet.EetService.TrzbaHlavickaType Hlavicka, Mews.Eet.EetService.TrzbaDataType Data, Mews.Eet.EetService.TrzbaKontrolniKodyType KontrolniKody, out object Item, out Mews.Eet.EetService.OdpovedVarovaniType[] Varovani) {
            Mews.Eet.EetService.OdeslaniTrzbyRequest inValue = new Mews.Eet.EetService.OdeslaniTrzbyRequest();
            inValue.Hlavicka = Hlavicka;
            inValue.Data = Data;
            inValue.KontrolniKody = KontrolniKody;
            Mews.Eet.EetService.OdeslaniTrzbyResponse retVal = ((Mews.Eet.EetService.EET)(this)).OdeslaniTrzby(inValue);
            Item = retVal.Item;
            Varovani = retVal.Varovani;
            return retVal.Hlavicka;
        }
        
        public System.Threading.Tasks.Task<Mews.Eet.EetService.OdeslaniTrzbyResponse> OdeslaniTrzbyAsync(Mews.Eet.EetService.OdeslaniTrzbyRequest request) {
            return base.Channel.OdeslaniTrzbyAsync(request);
        }
    }
}
